{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "from get_datasets.get_datasets import get_data_array, get_datasets\n",
    "import matplotlib.pyplot as plt\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "outputs": [
    {
     "data": {
      "text/plain": "  0%|          | 0/3883 [00:00<?, ?it/s]",
      "application/vnd.jupyter.widget-view+json": {
       "version_major": 2,
       "version_minor": 0,
       "model_id": "b007e526c5df4467b8bc6b52c9643ac1"
      }
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": "  0%|          | 0/2698 [00:00<?, ?it/s]",
      "application/vnd.jupyter.widget-view+json": {
       "version_major": 2,
       "version_minor": 0,
       "model_id": "80b71df5d73345aba97963084f9ced1e"
      }
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": "  0%|          | 0/390 [00:00<?, ?it/s]",
      "application/vnd.jupyter.widget-view+json": {
       "version_major": 2,
       "version_minor": 0,
       "model_id": "035bfb214d5b49a4945a70836ee06218"
      }
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": "  0%|          | 0/234 [00:00<?, ?it/s]",
      "application/vnd.jupyter.widget-view+json": {
       "version_major": 2,
       "version_minor": 0,
       "model_id": "0d0b4449aedf4b8c828fc067497f12b9"
      }
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "x_train, y_train, x_val, y_val, x_test, y_test = get_data_array(train_dir='/Users/yipengsun/Desktop/Edge '\n",
    "                                                                              'TPU/chest_xray_new/train',\n",
    "                                                                    test_dir='/Users/yipengsun/Desktop/Edge '\n",
    "                                                                             'TPU/chest_xray_new/test')\n"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-01-18 05:30:14.554564: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: AttributeError: module 'numpy' has no attribute 'bool'\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 154, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/PycharmProjects/Genetic_NAS/get_datasets/get_datasets.py\", line 69, in augment\n",
      "    return rand_aug(images=images.numpy())\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 2008, in __call__\n",
      "    return self.augment(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 1979, in augment\n",
      "    batch_aug = self.augment_batch_(batch, hooks=hooks)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3124, in _augment_batch_\n",
      "    batch = self[index].augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3395, in _augment_batch_\n",
      "    augmenter_active = self._get_augmenter_active(batch.nb_rows,\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3368, in _get_augmenter_active\n",
      "    augmenter_active = np.zeros((nb_rows, len(self)), dtype=np.bool)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/numpy/__init__.py\", line 284, in __getattr__\n",
      "    raise AttributeError(\"module {!r} has no attribute \"\n",
      "\n",
      "AttributeError: module 'numpy' has no attribute 'bool'\n",
      "\n",
      "\n",
      "2023-01-18 05:30:14.554623: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: AttributeError: module 'numpy' has no attribute 'bool'\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 154, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/PycharmProjects/Genetic_NAS/get_datasets/get_datasets.py\", line 69, in augment\n",
      "    return rand_aug(images=images.numpy())\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 2008, in __call__\n",
      "    return self.augment(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 1979, in augment\n",
      "    batch_aug = self.augment_batch_(batch, hooks=hooks)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3124, in _augment_batch_\n",
      "    batch = self[index].augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3395, in _augment_batch_\n",
      "    augmenter_active = self._get_augmenter_active(batch.nb_rows,\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3368, in _get_augmenter_active\n",
      "    augmenter_active = np.zeros((nb_rows, len(self)), dtype=np.bool)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/numpy/__init__.py\", line 284, in __getattr__\n",
      "    raise AttributeError(\"module {!r} has no attribute \"\n",
      "\n",
      "AttributeError: module 'numpy' has no attribute 'bool'\n",
      "\n",
      "\n",
      "2023-01-18 05:30:14.554912: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: AttributeError: module 'numpy' has no attribute 'bool'\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 154, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/PycharmProjects/Genetic_NAS/get_datasets/get_datasets.py\", line 69, in augment\n",
      "    return rand_aug(images=images.numpy())\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 2008, in __call__\n",
      "    return self.augment(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 1979, in augment\n",
      "    batch_aug = self.augment_batch_(batch, hooks=hooks)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3124, in _augment_batch_\n",
      "    batch = self[index].augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3395, in _augment_batch_\n",
      "    augmenter_active = self._get_augmenter_active(batch.nb_rows,\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3368, in _get_augmenter_active\n",
      "    augmenter_active = np.zeros((nb_rows, len(self)), dtype=np.bool)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/numpy/__init__.py\", line 284, in __getattr__\n",
      "    raise AttributeError(\"module {!r} has no attribute \"\n",
      "\n",
      "AttributeError: module 'numpy' has no attribute 'bool'\n",
      "\n",
      "\n",
      "2023-01-18 05:30:14.554924: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: AttributeError: module 'numpy' has no attribute 'bool'\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 154, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/PycharmProjects/Genetic_NAS/get_datasets/get_datasets.py\", line 69, in augment\n",
      "    return rand_aug(images=images.numpy())\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 2008, in __call__\n",
      "    return self.augment(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 1979, in augment\n",
      "    batch_aug = self.augment_batch_(batch, hooks=hooks)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3124, in _augment_batch_\n",
      "    batch = self[index].augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3395, in _augment_batch_\n",
      "    augmenter_active = self._get_augmenter_active(batch.nb_rows,\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3368, in _get_augmenter_active\n",
      "    augmenter_active = np.zeros((nb_rows, len(self)), dtype=np.bool)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/numpy/__init__.py\", line 284, in __getattr__\n",
      "    raise AttributeError(\"module {!r} has no attribute \"\n",
      "\n",
      "AttributeError: module 'numpy' has no attribute 'bool'\n",
      "\n",
      "\n",
      "2023-01-18 05:30:14.555047: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: AttributeError: module 'numpy' has no attribute 'bool'\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 154, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/PycharmProjects/Genetic_NAS/get_datasets/get_datasets.py\", line 69, in augment\n",
      "    return rand_aug(images=images.numpy())\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 2008, in __call__\n",
      "    return self.augment(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 1979, in augment\n",
      "    batch_aug = self.augment_batch_(batch, hooks=hooks)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3124, in _augment_batch_\n",
      "    batch = self[index].augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3395, in _augment_batch_\n",
      "    augmenter_active = self._get_augmenter_active(batch.nb_rows,\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3368, in _get_augmenter_active\n",
      "    augmenter_active = np.zeros((nb_rows, len(self)), dtype=np.bool)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/numpy/__init__.py\", line 284, in __getattr__\n",
      "    raise AttributeError(\"module {!r} has no attribute \"\n",
      "\n",
      "AttributeError: module 'numpy' has no attribute 'bool'\n",
      "\n",
      "\n",
      "2023-01-18 05:30:14.581696: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: AttributeError: module 'numpy' has no attribute 'bool'\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 154, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/PycharmProjects/Genetic_NAS/get_datasets/get_datasets.py\", line 69, in augment\n",
      "    return rand_aug(images=images.numpy())\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 2008, in __call__\n",
      "    return self.augment(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 1979, in augment\n",
      "    batch_aug = self.augment_batch_(batch, hooks=hooks)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3124, in _augment_batch_\n",
      "    batch = self[index].augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n",
      "    batch_inaug = self._augment_batch_(\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3395, in _augment_batch_\n",
      "    augmenter_active = self._get_augmenter_active(batch.nb_rows,\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3368, in _get_augmenter_active\n",
      "    augmenter_active = np.zeros((nb_rows, len(self)), dtype=np.bool)\n",
      "\n",
      "  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/numpy/__init__.py\", line 284, in __getattr__\n",
      "    raise AttributeError(\"module {!r} has no attribute \"\n",
      "\n",
      "AttributeError: module 'numpy' has no attribute 'bool'\n",
      "\n",
      "\n"
     ]
    },
    {
     "ename": "UnknownError",
     "evalue": "{{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} AttributeError: module 'numpy' has no attribute 'bool'\nTraceback (most recent call last):\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n    return func(device, token, args)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n    outputs = self._call(device, args)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 154, in _call\n    ret = self._func(*args)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n    return func(*args, **kwargs)\n\n  File \"/Users/yipengsun/PycharmProjects/Genetic_NAS/get_datasets/get_datasets.py\", line 69, in augment\n    return rand_aug(images=images.numpy())\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 2008, in __call__\n    return self.augment(*args, **kwargs)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 1979, in augment\n    batch_aug = self.augment_batch_(batch, hooks=hooks)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n    batch_inaug = self._augment_batch_(\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3124, in _augment_batch_\n    batch = self[index].augment_batch_(\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n    batch_inaug = self._augment_batch_(\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3395, in _augment_batch_\n    augmenter_active = self._get_augmenter_active(batch.nb_rows,\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3368, in _get_augmenter_active\n    augmenter_active = np.zeros((nb_rows, len(self)), dtype=np.bool)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/numpy/__init__.py\", line 284, in __getattr__\n    raise AttributeError(\"module {!r} has no attribute \"\n\nAttributeError: module 'numpy' has no attribute 'bool'\n\n\n\t [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]",
     "output_type": "error",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[0;31mUnknownError\u001B[0m                              Traceback (most recent call last)",
      "Cell \u001B[0;32mIn[7], line 3\u001B[0m\n\u001B[1;32m      1\u001B[0m train_ds_rand, val_ds, test_ds, train_ds \u001B[38;5;241m=\u001B[39m get_datasets(x_train, y_train, x_test, y_test, x_val, y_val)\n\u001B[0;32m----> 3\u001B[0m sample_images, _ \u001B[38;5;241m=\u001B[39m \u001B[38;5;28;43mnext\u001B[39;49m\u001B[43m(\u001B[49m\u001B[38;5;28;43miter\u001B[39;49m\u001B[43m(\u001B[49m\u001B[43mtrain_ds_rand\u001B[49m\u001B[43m)\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m      4\u001B[0m plt\u001B[38;5;241m.\u001B[39mfigure(figsize\u001B[38;5;241m=\u001B[39m(\u001B[38;5;241m10\u001B[39m, \u001B[38;5;241m10\u001B[39m))\n\u001B[1;32m      5\u001B[0m \u001B[38;5;28;01mfor\u001B[39;00m i, image \u001B[38;5;129;01min\u001B[39;00m \u001B[38;5;28menumerate\u001B[39m(sample_images[:\u001B[38;5;241m9\u001B[39m]):\n",
      "File \u001B[0;32m~/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py:787\u001B[0m, in \u001B[0;36mOwnedIterator.__next__\u001B[0;34m(self)\u001B[0m\n\u001B[1;32m    785\u001B[0m \u001B[38;5;28;01mdef\u001B[39;00m \u001B[38;5;21m__next__\u001B[39m(\u001B[38;5;28mself\u001B[39m):\n\u001B[1;32m    786\u001B[0m   \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[0;32m--> 787\u001B[0m     \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43m_next_internal\u001B[49m\u001B[43m(\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    788\u001B[0m   \u001B[38;5;28;01mexcept\u001B[39;00m errors\u001B[38;5;241m.\u001B[39mOutOfRangeError:\n\u001B[1;32m    789\u001B[0m     \u001B[38;5;28;01mraise\u001B[39;00m \u001B[38;5;167;01mStopIteration\u001B[39;00m\n",
      "File \u001B[0;32m~/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py:770\u001B[0m, in \u001B[0;36mOwnedIterator._next_internal\u001B[0;34m(self)\u001B[0m\n\u001B[1;32m    767\u001B[0m \u001B[38;5;66;03m# TODO(b/77291417): This runs in sync mode as iterators use an error status\u001B[39;00m\n\u001B[1;32m    768\u001B[0m \u001B[38;5;66;03m# to communicate that there is no more data to iterate over.\u001B[39;00m\n\u001B[1;32m    769\u001B[0m \u001B[38;5;28;01mwith\u001B[39;00m context\u001B[38;5;241m.\u001B[39mexecution_mode(context\u001B[38;5;241m.\u001B[39mSYNC):\n\u001B[0;32m--> 770\u001B[0m   ret \u001B[38;5;241m=\u001B[39m \u001B[43mgen_dataset_ops\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43miterator_get_next\u001B[49m\u001B[43m(\u001B[49m\n\u001B[1;32m    771\u001B[0m \u001B[43m      \u001B[49m\u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43m_iterator_resource\u001B[49m\u001B[43m,\u001B[49m\n\u001B[1;32m    772\u001B[0m \u001B[43m      \u001B[49m\u001B[43moutput_types\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43m_flat_output_types\u001B[49m\u001B[43m,\u001B[49m\n\u001B[1;32m    773\u001B[0m \u001B[43m      \u001B[49m\u001B[43moutput_shapes\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43m_flat_output_shapes\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    775\u001B[0m   \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[1;32m    776\u001B[0m     \u001B[38;5;66;03m# Fast path for the case `self._structure` is not a nested structure.\u001B[39;00m\n\u001B[1;32m    777\u001B[0m     \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39m_element_spec\u001B[38;5;241m.\u001B[39m_from_compatible_tensor_list(ret)  \u001B[38;5;66;03m# pylint: disable=protected-access\u001B[39;00m\n",
      "File \u001B[0;32m~/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py:3017\u001B[0m, in \u001B[0;36miterator_get_next\u001B[0;34m(iterator, output_types, output_shapes, name)\u001B[0m\n\u001B[1;32m   3015\u001B[0m   \u001B[38;5;28;01mreturn\u001B[39;00m _result\n\u001B[1;32m   3016\u001B[0m \u001B[38;5;28;01mexcept\u001B[39;00m _core\u001B[38;5;241m.\u001B[39m_NotOkStatusException \u001B[38;5;28;01mas\u001B[39;00m e:\n\u001B[0;32m-> 3017\u001B[0m   \u001B[43m_ops\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mraise_from_not_ok_status\u001B[49m\u001B[43m(\u001B[49m\u001B[43me\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mname\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m   3018\u001B[0m \u001B[38;5;28;01mexcept\u001B[39;00m _core\u001B[38;5;241m.\u001B[39m_FallbackException:\n\u001B[1;32m   3019\u001B[0m   \u001B[38;5;28;01mpass\u001B[39;00m\n",
      "File \u001B[0;32m~/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/framework/ops.py:7215\u001B[0m, in \u001B[0;36mraise_from_not_ok_status\u001B[0;34m(e, name)\u001B[0m\n\u001B[1;32m   7213\u001B[0m \u001B[38;5;28;01mdef\u001B[39;00m \u001B[38;5;21mraise_from_not_ok_status\u001B[39m(e, name):\n\u001B[1;32m   7214\u001B[0m   e\u001B[38;5;241m.\u001B[39mmessage \u001B[38;5;241m+\u001B[39m\u001B[38;5;241m=\u001B[39m (\u001B[38;5;124m\"\u001B[39m\u001B[38;5;124m name: \u001B[39m\u001B[38;5;124m\"\u001B[39m \u001B[38;5;241m+\u001B[39m name \u001B[38;5;28;01mif\u001B[39;00m name \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;129;01mnot\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m \u001B[38;5;28;01melse\u001B[39;00m \u001B[38;5;124m\"\u001B[39m\u001B[38;5;124m\"\u001B[39m)\n\u001B[0;32m-> 7215\u001B[0m   \u001B[38;5;28;01mraise\u001B[39;00m core\u001B[38;5;241m.\u001B[39m_status_to_exception(e) \u001B[38;5;28;01mfrom\u001B[39;00m \u001B[38;5;28mNone\u001B[39m\n",
      "\u001B[0;31mUnknownError\u001B[0m: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} AttributeError: module 'numpy' has no attribute 'bool'\nTraceback (most recent call last):\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n    return func(device, token, args)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n    outputs = self._call(device, args)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 154, in _call\n    ret = self._func(*args)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n    return func(*args, **kwargs)\n\n  File \"/Users/yipengsun/PycharmProjects/Genetic_NAS/get_datasets/get_datasets.py\", line 69, in augment\n    return rand_aug(images=images.numpy())\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 2008, in __call__\n    return self.augment(*args, **kwargs)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 1979, in augment\n    batch_aug = self.augment_batch_(batch, hooks=hooks)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n    batch_inaug = self._augment_batch_(\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3124, in _augment_batch_\n    batch = self[index].augment_batch_(\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 641, in augment_batch_\n    batch_inaug = self._augment_batch_(\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3395, in _augment_batch_\n    augmenter_active = self._get_augmenter_active(batch.nb_rows,\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/imgaug/augmenters/meta.py\", line 3368, in _get_augmenter_active\n    augmenter_active = np.zeros((nb_rows, len(self)), dtype=np.bool)\n\n  File \"/Users/yipengsun/miniforge3/envs/Genetic_NAS/lib/python3.10/site-packages/numpy/__init__.py\", line 284, in __getattr__\n    raise AttributeError(\"module {!r} has no attribute \"\n\nAttributeError: module 'numpy' has no attribute 'bool'\n\n\n\t [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]"
     ]
    }
   ],
   "source": [
    "image_size = 128\n",
    "\n",
    "train_ds_rand, val_ds, test_ds, train_ds = get_datasets(x_train, y_train, x_test, y_test, x_val, y_val)\n",
    "\n",
    "sample_images, _ = next(iter(train_ds_rand))\n",
    "plt.figure(figsize=(10, 10))\n",
    "for i, image in enumerate(sample_images[:9]):\n",
    "    ax = plt.subplot(3, 3, i + 1)\n",
    "    plt.imshow(image.numpy().astype(\"int\"))\n",
    "    plt.axis(\"off\")"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
